tcdi/plrust

Cargo.toml
src/lib.rs
src/plrust.rs

Adds tests! We don't have CI yet, but these do pass. CI comes next.

feat: add tests

---

src/lib.rs
src/plrust.rs

Add update test

---

.github/workflows/ci.yml

Whoops! We weren't testing that version.

Add pg14 to CI

---

src/plrust.rs

This replaces the `Option` we were using for late initialization with a `once_cell::unsync::Lazy`. It's more appropriate.

Use once_cell::Lazy for LOADED_SYMBOLS

---

.github/workflows/ci.yml

We should check `cargo fmt` isn't changing on PRs.

Add rustfmt check to CI

---

src/lib.rs

Add an example using `pgx`'s SPI.
Resolves #14.

Add SPI example

---

src/lib.rs

I think the reason the test failed is spurious Nix/Mac stuff?

Avoid clobbering functions in tests if unnecessary

---

.github/workflows/ci.yml
src/plrust.rs

Use not-Nix so we can have not-sandboxed tests so we can test random user crates etc easier.

Different CI

---

README.md
src/lib.rs

Does some basic `README.md` touchups.

Readme touchups

---

Cargo.lock
src/tests.rs

I am trying to reproduce an issue I discovered.

Make deps test use owo-colors over Zalgo

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
build
rust-toolchain.toml
src/tests.rs
src/user_crate/mod.rs
src/user_crate/state_generated.rs
src/user_crate/target.rs

Opening this PR to test the postgrestd revision against CI.
Fairly minimal changes to allow fake """namespacing""" of a test.

Another postgrestd

---

.github/workflows/ci.yml
build
src/tests.rs

Test panics don't kill the database

---

README.md

A very trivial change, however it took me a few minutes to understand what was needed ( the examples are clear enough).

Document the plrust.pg_config parameter

---

.licensure.yml
LICENSE.md

It is the PostgreSQL license

---

build

Attempt to fix pgx build using --locked

---

doc/architecture.md

tcdi/plrust#69 Updated document for merge errors.

Update architecture document for merge errors.

---

.github/scripts/load_cache.sh
.github/scripts/save_cache.sh
.github/workflows/ci.yml

All work here is an attempt to bring down the build times for plrust on arm64. Right now the builds are roughly 30 minutes give or take. I am fairly certain we can get that down to a lower number.
Addresses https://github.com/tcdi/plrust/issues/84

Speeds up arm64 build times

---

plrust/src/tests.rs

Enable `#[link_section]` test

---

plrust/src/user_crate/build.rs
plrust/src/user_crate/crate_variant.rs
plrust/src/user_crate/crating.rs
plrust/src/user_crate/loading.rs
plrust/src/user_crate/ready.rs
plrust/src/user_crate/verify.rs

Terse docs for mod user_crate

---

plrust/src/plrust.rs
plrust/src/plrust_proc.rs
plrust/src/tests.rs

Recursively executing a plrust function is easy doable by putting the `UserCrate<FnReady>` behind a `Rc`.

fix issue #79

---

.github/workflows/ci.yml
Cargo.lock
plrust/build
plrust/src/plrust.rs
plrust/src/tests.rs
plrust/src/user_crate/crating.rs
plrust/src/user_crate/mod.rs

This also resolves some random compilation issues that ~~could hypothetically occur~~ will definitely occur until we actually cut the pgx release and bump.

Fix up PL/Rust for `pg_sys::Oid` redesign

---

.github/workflows/ci.yml
README.md
plrust/Cargo.toml
plrust/build
plrust/src/tests.rs
plrust/src/user_crate/target.rs

 Declare postgres as vendor in tuples 

---

.github/workflows/ci.yml
README.md
plrust/Cargo.toml
plrust/build
plrust/src/error.rs
plrust/src/gucs.rs
plrust/src/lib.rs
plrust/src/plrust_proc.rs
plrust/src/target.rs
plrust/src/tests.rs
plrust/src/user_crate/build.rs
plrust/src/user_crate/crating.rs

I'll come back to this tomorrow...

More Cross Compilation Work

---

README.md

There isn't really a way for us to make `?` on an Option work here, so I just unwrapped.

Fix some broken code in the README

---

trusted-pgx/src/lib.rs

Add pgx::log

---

plrustc/plrustc/src/main.rs

Outside of work, I happened to write another rustc_driver wrapper. I managed to make it significantly simpler than what we're doing in plrustc, so here's a commit using that approach instead.

Cleanup/rewrite plrustc main.rs

---

.github/workflows/ci.yml
plrustc/plrustc/src/lints.rs
plrustc/plrustc/uitests/print_macros.stderr

Somehow this started failing. Add these to CI to prevent that from happening again.
CC @BradyBonnette

Fix failing uitests and add them to CI

---

Cargo.lock
plrust-trusted-pgx/Cargo.toml
plrust/Cargo.toml
plrust/src/gucs.rs
upgrade-deps.sh

along with other deps that have new versions.

upgrade pgx to 0.7.3

---

doc/src/install-plrust.md
doc/src/plrust.md
doc/src/trusted-untrusted.md

This PR is focused on improving the installation section.
There is now a summary of installation steps at beginning to set the user's expectations.  I expanded the text in many places to better explain each step.  Add more links throughout the page.

Documentation: Improve installation section

---

doc/src/use-plrust.md

Corrects details about unnamed parameters.  A bit of cleanup and expansions.
Many of the words in this PR are from @workingjubilee :+1:

Documentation: Improve usage

---

plrustc/plrustc/src/main.rs

Previous version would allow `/tmp/foobar` and `/tmp/foo`, since I used `str::starts_with`. Thankfully, `Path::starts_with` exists in the stdlib, which exists to literally solve this exact issue (it compares whole components) — I just didn't know it existed.
Fixing that allows simplifying the code a good amount.

Fix path traversal bug

---

plrustc/plrustc/src/main.rs

Just some minor cleanup. We should never hit these anyway, hopefully.

Use `early_error` to emit early errors

---

README.md

- fix incorrect information
- minor wordsmithing
- add Discord invite link
- address issue #285

README.md cleanups:

---

Dockerfile.try
doc/src/install-plrust-on-debian-ubuntu.md
plrust/build
plrustc/build.sh
plrustc/plrustc/src/lints/static_impls.rs
plrustc/plrustc/src/lints/tuple_struct_self_pattern.rs
plrustc/plrustc/src/main.rs
plrustc/rust-toolchain.toml
rust-toolchain.toml

Not fully tested, but compiles. (I'll let CI do the testing)

Update to Rust 1.69.0

---

Dockerfile.try
doc/src/install-plrust-on-debian-ubuntu.md
plrust/build
plrustc/build.sh
plrustc/plrustc/src/main.rs
plrustc/plrustc/uitests/ice_hook.stderr
plrustc/rust-toolchain.toml
rust-toolchain.toml

This is just the plrustc and plrust changes. The postgrestd changes will be up soon, but are not yet (git subtree is slow as hell so I did this while waiting).

Bump versions to 1.70.0 

---

plrust/src/tests.rs

The test is essentially a cut-n-paste of the long example in the docs.

A test for UDT/composite_type support

---

.github/workflows/docs.yml

Note that this is going directly into `main`

Add plrust.io CNAME file

---

.github/workflows/docs.yml

Adds CNAME file to correct location for doc generation
