tcdi/plrust

.envrc, flake.lock, flake.nix
Add a super basic Nix flake with just inherited checks/devShell to get the project developer friendly.
More context: https://github.com/zombodb/pgx/pull/124
More to come! :)
=> feat: nix flake shell/checks

src/lib.rs
`pgx` 0.4.0 series has good support for this new attribute and it removes the rather confusing documentation otherwise generated.
=> Use sql attr for plrust_call_handler

src/plrust.rs
We have some workaround in x86 Mac which we weren't correctly feature flagging in #12 .
=> Repair cfg selection on x86 Mac

src/plrust.rs
Claws back as many lines from miscellaneous control flow and formatting as possible without actually making any functional changes to the code or even disrupting it much, mostly by preferring more immutable / declarative constructs.
=> Less is more

src/plrust.rs
This is being expected to be available several times anyways, so
instead just unwrap once, reducing the layers of nesting required.
=> Eagerly unwrap argtypes

Cargo.lock, Cargo.toml, flake.lock, src/error.rs, src/gucs.rs, src/lib.rs, src/logging.rs, src/plrust.rs
Improves error handling code in PL/Rust.
Includes:
* `thiserror`
* `eyre`/`tracing` wired up to not interfere with pgx
* Spantraces and error sections supported
* *Most* unwraps turned into errors, this is just a first pass.
* `tracing_level` GUC for customizing the log level of PL/Rust itself
* `#[pg_extern]` functions now wrap functions which return errors, and handle them.
* Updates flake for CI
=> Improved Error handling

Cargo.lock, Cargo.toml, src/lib.rs, src/plrust.rs, src/postalloc.rs
This doesn't include out-of-line crates I was fooling around with that are referenced here, as I wasn't sure what the best restructuring of things would be at the time, so I just pushed them somewhere else. At the moment I have just been using more direct FFI calls to Postgres for the allocator's implementation, but I imagine with some refactoring of PGX, a possible more sophisticated implementation might mesh itself more seamlessly with existing code in PGX. Or not.
One of the unresolved questions is "wait, why do tests randomly fail if I use `palloc` instead of `SPI_palloc`?"
=> "post-alloc" skeleton

Cargo.lock, build
Most common user error recently has been pgx and cargo-pgx versions being misaligned.
Simply force them in the build script as a temporary solution until releases are cut.
=> Guarantee pgx and cargo-pgx version in ./build

src/plrust.rs, src/user_crate/mod.rs, src/user_crate/state_built.rs, src/user_crate/state_generated.rs, src/user_crate/state_loaded.rs, src/user_crate/state_provisioned.rs
FunctionOids are unique within the database but not across it. It's possible for two PL/Rust functions to share the same fn_oid across different databases leading to overwriting the same function, or accessing it.
To prevent this include db_oid when constructing the name to guarantee uniqueness of the files
Note this might be unnecessary by the time https://github.com/tcdi/plrust/issues/28 is addressed but until then it seems like it'd be better to avoid this potential case.
=> Include db_oid when writing/referencing the binary on disk

Cargo.lock, src/lib.rs, src/tests.rs, src/user_crate/crate_variant.rs, src/user_crate/state_generated.rs
This brings PL/Rust up to date with the latest diffs in pgx as a direct result of tcdi/pgx#615's new Rust-to-SQL-and-back type mapping, specifically lining us up with https://github.com/tcdi/pgx/commit/3894728ab8ed732a3087a72363f32ebe0ddd7c8b. Very shortly will come pgx 0.5.0-beta.1 which should settle the major diffs insofar as PL/Rust is concerned.
=> Update for pgx#615: New SQL type mapping

Cargo.lock, src/tests.rs, src/user_crate/mod.rs, src/user_crate/state_generated.rs
It was noticed that a few plrust tests were broken after PGX introduced `pgx::prelude`. See here https://github.com/tcdi/pgx/pull/699
The work here aims to fix those tests.
=> Fixes broken tests due to introduction of pgx::prelude

.gitignore
For those of us that use VSCode, it's probably advisable to add this to `.gitignore`.
=> Adds .vscode workdir to gitignore

src/lib.rs, src/plrust.rs
This doesn't cover the entire crate due to the issue noted in https://github.com/tcdi/pgx/pull/707.
=> Partially apply `#[deny(unsafe_op_in_unsafe_fn)]`

Cargo.toml, src/plrust.rs
There's no guarantee that when the database is restored it'll land on the same host architecture as when the object was compiled.
This lays the ground work to at least avoid running the object in question
We replace '-' in the host triple with '_' because it's not recognized as a valid identifier
=> Include architecture in name of plrust compiled objects

README.md
If cargo expand is used on plrust, it embeds the README.md in the expansion inside a block doc-comment. A Rust syntax highlighter will thus interpret the bash in the README.md as Rust. This means some forms of glob syntax are seen as ending the comment instead.
The result is that everything has broken highlighting, and if we ever wanted to actually include the README.md, it might even break compilation!
Fortunately, Rust defines /* */ to have balanced nesting rules. Thus, putting a Rust block-comment-open inside an HTML comment, which is invisible when the README.markdown is viewed as HTML, fixes this for Rust syntax handlers that don't also know Markdown.
=> Fix Rust highlighting for cargo expand

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/lib.rs, src/tests.rs, src/user_crate/mod.rs, src/user_crate/state_generated.rs
This adds a new feature, `"verify"`, to PL/Rust, which is set by default at compilation time. It also makes all code written for PL/Rust more strict, opting in to RFC 2585's `unsafe_op_in_unsafe_fn` lint by default, to make it harder to escape `unsafe` detection with or without the `"verify"` feature. This is possible due to tcdi/pgx#707.
Together these are expected to take care of most ways of sneaking `unsafe` into a PL/Rust function, however this basic prototype does not handle a number of possible routes for recursion, crate dependencies, et cetera.
=> Add prototype unsafe checks in PL/Rust

Cargo.lock, Cargo.toml, src/tests.rs, src/user_crate/mod.rs, src/user_crate/state_generated.rs
Everything bumps and plrust fn are now built with the "plrust" feature flag. This also means it doesn't have to use the latest git branch as a patch anymore.
=> Update to pgx 0.5.0-beta.1

src/tests.rs, src/user_crate/crate_variant.rs, src/user_crate/state_generated.rs
`HashMap<K, V, S>`, like most hash-keyed collection types,
does not order entries deliberately, instead simply hashing keys.
Unlike most hashed types, `HashMap<K, V, S = RandomState>` defaults
to using SipHash with a random seed to its hashing logic, which
can result in an essentially nondeterministic order in the map.
Even more peculiarly, `HashMap<K, V, RandomState>` iterates randomly,
because it does not use the key's ordering to iterate, but
simply starts at one entry and loops "in order" (i.e. random order).
By collecting arguments into a `HashMap`, then unpacking that map,
they were given a different ordinal position. This resulted in
calling with different orderings of arguments, as the arguments
only acquire names inside the Rust `fn` body: before that they
have only a number and …
=> Use `Vec<syn::FnArg>` for deterministic arg order 

src/user_crate/mod.rs
We can't map to a specific `Numeric<P, S>` as Postgres doesn't store the "typmod" values in the `pg_proc` catalog, so by the time we create the function, those are lost to us.
I don't view this as a big deal, tho.  Users can use `AnyNumeric::rescale<P, S>().into()` to return a `AnyNumeric` that's been truncated/expanded to a particular precision and scale.  Alternatively, it can be handled at the SQL level, which I suspect is what most people do today with languages like plpgsql.
NOTE:  This PR will require a version of pgx > 0.5.6.
=> Map `NUMERIC` to pgx 0.6's `AnyNumeric`

Cargo.lock, Cargo.toml, README.md, build.rs, src/error.rs, src/hooks.rs, src/lib.rs, src/plrust.rs, src/plrust_proc.rs, src/tests.rs, src/user_crate/mod.rs, src/user_crate/state_generated.rs, src/user_crate/state_provisioned.rs
Move the ultimate storage of a plrust compiled function from disk to an extension table named `plrust.plrust_proc`.
The compilation process now cleans up after itself (we no longer leave any function-specific artifacts on disk, other than the shared `${PLRUST.WORK_DIR}target/` directory), and the .so bytes are inserted into the new `plrust.plrust_proc` table, tagged with the host's "target_triple", as the compiled pl/rust extension understands it.
Also enables plrust to properly work with `DROP FUNCTION`, `DROP SCHEMA`, and `ALTER FUNCTION` when a `LANGUAGE plrust` function is involved in one of those statements.  For the first two, we remove the corresponding entires in our `plrust.plrust_proc` table, for the latter we let everything pass except changes to the `STRICT` property.
The …
=> Store compiled shared object files in a new extension table

src/lib.rs, src/plrust.rs, src/user_crate/mod.rs, src/user_crate/state_built.rs, src/user_crate/state_generated.rs, src/user_crate/state_loaded.rs
The purpose of applying this lint on a crate-wide basis is to allow us to more easily find, audit, and verify `unsafe` code throughout the crate. A handler function that does most of the work during coalescing the actual function, unfortunately, is currently exempted, because it will otherwise have severe merge conflicts with https://github.com/tcdi/plrust/pull/122.
I have deliberately avoided adding `// SAFETY` annotations in the `user_crate` cases because I will find my current notes unsatisfactory (read: almost nonexistent) and I intend to come back later with the clippy lint that will force me to find them all and properly document them anyways.
=>  Crate-wide `#![deny(unsafe_op_in_unsafe_fn)]`

src/error.rs, src/hooks.rs, src/lib.rs, src/pgproc.rs, src/plrust.rs, src/plrust_proc.rs, src/user_crate/mod.rs, src/user_crate/state_built.rs, src/user_crate/state_generated.rs, src/user_crate/state_loaded.rs, src/user_crate/state_provisioned.rs
This PR, which is based on the changes in #122, reloads a function if it was changed by a concurrent transaction.  
It also cleans up our various syscache usages and centralizes them into a new type named `PgProc` in the `pgproc.rs` module.
Note, it'll be easier to review this after #122 is merged.
=> Reload function.so when the function changes

src/hooks.rs, src/lib.rs, src/pgproc.rs, src/user_crate/state_generated.rs
This finally gets us to no-exceptions `#![deny(unsafe_op_in_unsafe_fn)]`, thanks to #124!
=> Now `#![forbid(unsafe_op_in_unsafe_fn)]`

plrust/src/plrust.rs, plrust/src/plrust_proc.rs, plrust/src/user_crate/mod.rs, plrust/src/user_crate/state_built.rs, plrust/src/user_crate/state_generated.rs, plrust/src/user_crate/state_loaded.rs, plrust/src/user_crate/state_provisioned.rs, plrust/src/user_crate/state_validated.rs
This allows PL/Rust to feed on a filesystem that has been configured to only allow "write-once read-many" or WORM. It fixes https://github.com/tcdi/plrust/issues/139 as one might imagine.
The unusual path remapping hack is only for this PR, I intend to fix it in the next. For various reasons I don't want to chance losing the git history for these files (yet).
=> Diet of WORMs

Cargo.lock, plrust/Cargo.toml, plrust/src/hooks.rs, plrust/src/plrust_proc.rs, plrust/src/tests.rs, plrust/src/user_crate/crating.rs, plrust/src/user_crate/mod.rs
For now, lets have plrust use pgx' `develop` branch, so we can move forward with the "trusted-pgx" crate.
This PR makes that change and updates the code (mostly around Spi) so that it compiles.
Also note that the user function dependency on `pallocator` has been commented out -- I believe that needs some TLC against pgx:develop as well.
=> Change to use the `pgx:develop` branch

plrust/src/plrust_proc.rs, plrust/src/tests.rs
See the comments that @JohnHVancouver made on his PR #140, but this is the right way to do this.  Doesn't require going through SPI to lookup the object identifier.
=> use `pg_identify_object()` value as the pkey for `plrust.plrust_proc`

plrust/src/tests.rs, plrust/src/user_crate/ready.rs
Properly protect the FFI boundary when calling the loaded user function so that the stack will properly unwind in the face of rust panics and Postgres errors.
=> fix issue #78

Cargo.lock, Cargo.toml, plrust/src/user_crate/crating.rs, plrust/src/user_crate/mod.rs, trusted-pgx/Cargo.toml, trusted-pgx/src/lib.rs
Add a new module, `trusted-pgx` which exports the bare minimum things necessary for a standard plrust user function to not only compile, but to also pass safety checks, and to otherwise be usable to the developer.
- We have a chicken/egg problem right now as the `trusted-pgx` crate isn't published, which is why its dependency is hardcoded to this repo + branch
- The user crate dependency on `pallocator` has been commented out.  Including it causes compilation errors
- Unclear if `trusted-pgx` exports everything a plrust user function will need.  I think it's probably pretty close
- All tests pass locally
=> Introduce a `trusted-pgx` module

Cargo.lock, plrust/Cargo.toml, plrust/src/tests.rs, plrust/src/user_crate/ready.rs
When running on Linux we create an anonymous file (via `memfd_create()`), write the user function shared library bytes to it, and "dlopen()" from there.
On all other platforms we maintain our current solution of writing a temporary file to the configured `plrust.work_dir`.
=> On Linux, `dlopen()` user functions from a memory-mapped file 

Cargo.lock, plrust/Cargo.toml, plrust/build, plrust/src/user_crate/crating.rs, trusted-pgx/Cargo.toml
This also changes the expected branch for the "trusted-pgx" dependency to the `main` branch.
~~Because of that change, CI is going to fail.  But I'll merge anyways and then it should pass in the main branch.  Tests pass locally for me.~~
No, it shouldn't.  That crate is already in `main`.
=> upgrade pgx dependency to 0.7.0-beta.1

plrust/src/tests.rs
This test was useful for noticing failures due to problems with PGX's unwinding correctness. It is no longer useful, and has begun to be a source of transient problems.
It has however revealed something else that might be useful to study more closely, but that is something I will do in a followup.
=> Rip out sleepy_boi test

README.md, doc/architecture.md, plrust/src/tests.rs, plrust/src/user_crate/crate_variant.rs, plrust/src/user_crate/crating.rs, plrust/src/user_crate/mod.rs, trusted-pgx/src/lib.rs
This does the work, which was mostly updating our tests, to change the wrapper function plrust writes for user functions to return `Result<Option<T>, Box<dyn Error>>` instead of a plain `Option<T>`.
This, I truly believe, is an ergonomics improvement now that `Spi` is based on returning Results.  And this is a thing we need to do know as it's a backwards incompatible ABI change along with a backwards incompatible code change.
=> plrust functions now return `Result<Option<T>>`

plrust/build
=> Only specify CARGO_TARGET_..._LINKER if not already specified, and ensure it and `STD_TARGETS` are exported and avaliable to `./run`.

plrust/src/tests.rs
This adds a new test and rearranges the unsafe test functions slightly (which has a somewhat confusing diff because the tests are very similar).
=> Test `#[export_name]` is blocked

Cargo.lock, README.md, plrust/Cargo.toml, plrust/src/gucs.rs, plrust/src/plrust.rs, plrust/src/tests.rs, plrust/src/user_crate/build.rs, plrust/src/user_crate/mod.rs, plrust/src/user_crate/verify.rs
Turns out Postgres itself, via its internal `get_configdata()` function knows everything `pg_config` does.  So we convert all the `ConfigData` key/value pairs into environment variables for pgx-pg-sys to use during its build.rs.  
This relies on the changes in https://github.com/tcdi/pgx/pull/1019 and https://github.com/tcdi/pgx/pull/1020.
=> Remove the `plrust.pg_config` GUC

plrust/src/user_crate/build.rs
Not all users of PL/Rust will have access to the file-system to manually clean up source code when compilation fails.
Add cleanup when compilation fails, the error is already outputted to the end user.
Also fix compilation on x86 mac, it complains about crate_name being behind a shared reference otherwise
=> Cleanup source crate after compilation fails

plrust/src/hooks.rs, plrust/src/lib.rs
`plrust` will no longer raise an ERROR if a function is being ALTERed in a database that doesn't also have the `plrust` extension created.
=> fix issue #183

Cargo.lock, README.md, plrust/Cargo.toml, plrust/src/gucs.rs, plrust/src/user_crate/build.rs, plrust/src/user_crate/mod.rs, plrust/src/user_crate/verify.rs
Debian-based distro-managed Postgres installations (such as Ubuntu) seem to clear the `$PATH` environment variable when Postgres starts.  This means that plrust can't find the system commands such as `cargo` and `cc` that it needs to compile user functions (there are probably others).
If the `$PATH` is missing (or the empty string), we'll hardcode it to `~/.cargo/bin:/usr/bin` when executing `cargo`.  However, if the user has set the `plrust.PATH_override` GUC, then we will **always** use that when executing `cargo`.
=> Set a `$PATH` when there isn't one

plrust/src/tests.rs
~~CI intentionally fails here, it requires https://github.com/tcdi/postgrestd/pull/23 for it to pass.~~ That landed, so it passes now.
Fixes #172
=> Add a test for include_str!

Cargo.lock, README.md, plrust/Cargo.toml, plrust/build, plrust/src/user_crate/crating.rs, trusted-pgx/Cargo.toml, upgrade-deps.sh
Specifically, get pgx upgraded to 0.7.1.
- upgraded the `toml` crate to 0.7.1 and fixed the code.
- Added `upgrade-deps.sh` to make this easier (it requires that `cargo-edit` be installed locally)
=> Upgrade dependencies

Cargo.lock, plrust/Cargo.toml, plrust/plrust.control, trusted-pgx/Cargo.toml
Bumps version numbers and updates Cargo metadata
=> bump version to 1.0.0-beta.1

plrust/src/user_crate/crate_variant.rs, plrust/src/user_crate/crating.rs, plrust/src/user_crate/mod.rs
This adds a `<'a>` lifetime to all user functions so that the few cases where arguments are borrowed (`&'a str`) and return types might borrow (`SetOfIterator<'a, ...>)` can do so.
Also blindly adds the `#[allow(unused_lifetime)]` annotation to all instances of user functions so that compilation warnings won't happen in the cases where all args/return don't borrow.
=> Fix issue #200

plrust/src/user_crate/crating.rs
This isn't necessary for compilation, causes problems, and massively slows down compilation.
We don't need to be using 1 CGU either.
These changes may penalize performance slightly. However, compilation times have been enough of a recurring concern that we must balance runtime and compilation time as we proceed.
=> Stop using LTO to build function crates

plrust/src/user_crate/crating.rs, plrust/src/user_crate/lint.rs
Fixes part of #218.
When `plrust.compile_lints = '' ` is set to empty, this allows compilation to still proceed.
=> Allow disabling linting when it is set to an empty string

LINTS.md, plrustc/plrustc/src/lints.rs, plrustc/plrustc/uitests/fn_traits.rs, plrustc/plrustc/uitests/fn_traits.stderr
Wasn't able to get any of these to work like function pointers do, but it seems like they have the same soundness holes nonetheless (which makes sense).
=> Lint against `dyn Fn{,Mut,Once}`

plrust/src/user_crate/mod.rs
Reported elsewhere. Trivial fix for something like:
```sql
create or replace function foo() returns text  IMMUTABLE STRICT  LANGUAGE PLRUST AS  $$
 [code]
     Ok(Some("foobar".to_string()))
 // $$;
```
=> Add newline before closing block

plrust/src/pgproc.rs, plrust/src/user_crate/crating.rs
We don't support these things yet, and this improves the error message from
```
ERROR:  assertion failed: `(left == right)`
left: `1`,
right: `0`
```
to
```
ERROR:  not yet implemented: OUT arguments   # (or `RETURNS TABLE functions` or `INOUT arguments`)
```
=> address issue #197 by blocking RETURNS TABLE, OUT and INOUT function argument

README.md, plrustc/README.md
Most of the `plrustc` readme was written when things were in an intermediate state that looked pretty different from where we ended up. I've completely ditched the installation guide (it was stale, and we should document that in the main README instead), and (I think) removed all the inaccuracies.
I've also added mention of the environment variables `plrustc` uses to find the sysroot. They're basically the same ones that miri, clippy, etc. might use, although with `PLRUSTC_SYSROOT` acting as the override var (rather than something like `MIRI_SYSROOT`, which is clearly not ours to use).
=> Remove some stale documentation from plrustc's readme, and add mention of some of the env vars it uses to the main readme

plrustc/plrustc/build.rs
This was not needed after the overhaul. It's harmless, but makes builds very slightly slower (plrustc already builds so fast that it basically doesn't matter at all).
We should wait for #238 before landing this, since that adds plrustc CI. This does not need to be in the next release.
=> Remove pointless build.rs from plrustc

README.md
This is probably not the ideal documentation, but it's something.
=> Add caveat around security/soundness to README.md

README.md, plrust/src/user_crate/cargo.rs
Meant to do this a while ago. This may or may not clear up the issues we had with sccache (no idea), but we shouldn't inherit this from the user env.
=> Remove `RUSTC_WRAPPER` from the env if set

plrustc/plrustc/src/main.rs
Cargo will sometimes spill args to a separate file if they're too long, passing them as `@path/to/argfile`, so we should ensure they're expanded. Thankfully, there's an easy to use function in rustc_driver for this.
=> Correctly expand args given to plrustc

plrustc/plrustc/src/lints.rs, plrustc/plrustc/src/main.rs, plrustc/plrustc/uitests/ice_hook.rs, plrustc/plrustc/uitests/ice_hook.stderr
I wrote some buggy code and noticed we tell the user to file a bug against `rust-lang/rust`. That seems bad since it will probably annoy people upstream if they have to field plrustc issues.
Most of the complexity here is:
1. Allowing this to be mor tested.
2. Setting up the code needed to report a one-shot error from a location that doesn't have access to the error reporting machinery.
The second of these is the more confusing bit, but it's also something we will want anyway in the long term (at which point I'll factor it out).
=> Avoid linking to `rust-lang/rust`'s issue tracker if `plrustc` panics

plrust/src/pgproc.rs, plrust/src/tests.rs, plrust/src/user_crate/crate_variant.rs, plrust/src/user_crate/crating.rs, plrust/src/user_crate/mod.rs
PL/Rust does not support unnamed function arguments.  And more generally, PL/Rust does not support function argument names that aren't also valid Rust identifiers.
This catches all of these situations and raises the appropriate SQL error.
=> Fix issue #255

.github/workflows/ci.yml
This should provide us with the ability to kick off a build whenever, similar to PGX. The ability will only show up once this gets into `main` however
=> Adds workflow_dispatch to CI

doc/src/SUMMARY.md, doc/src/rules-regulations.md, doc/src/update-plrust.md
Should finish #255.  Updates details about function argument names being required, etc.  Moved to new rules and regs section and made notes of additional examples to document.
Improves plrust update notes. Everything needs updating when installing PL/Rust updates.
=> Document #255

plrust/src/user_crate/cargo.rs
This has bugged me for a billion years. This flag does nothing on non-macOS platforms, and it's honestly surprising that it isn't an error on other linkers.
=> Only set `-Clink-args=-Wl,-undefined,dynamic_lookup` on macos

Cargo.lock, doc/src/config-pg.md, plrust-trusted-pgx/Cargo.toml, plrust/Cargo.toml, plrustc/Cargo.lock, plrustc/plrustc/Cargo.toml
We are excited to present PL/Rust v1.0.0.  Writing Postgres UDFs in Rust has never been easier (mostly because it hasn't been possible)!
PL/Rust is a loadable, trusted procedural language handler enabling developers to create PostgreSQL functions in the Rust programming language. Unlike other procedural languages, PL/Rust functions are not interpreted. Instead, the definition you supply to `CREATE FUNCTION ... LANGUAGE plrust` is wrapped in Rust, compiled to native machine code, and dynamically loaded.
Many of the usual tradeoffs of compilation apply:
- Compilation can be slow
- Execution can be very fast, often ×10 faster than PL/pgSQL!
- Types are static and must be explicitly handled
- Code can be fully analyzed and errors caught at compile time
- PL/Rust must understand both what it …
=> Prepare v1.0.0

doc/src/install-plrust.md, doc/src/install-prerequisites.md, doc/src/rules-regulations.md, plrust/src/lib.rs
PL/Rust can't support databases that aren't UTF8 because of Rust's requirements around Strings being proper UTF8.  This PR causes `CREATE EXTENSION plrust` to raise an ERROR in this case:
```sql
[v14.6][2495941] plrust=# create extension plrust;
ERROR:  PL/Rust only supports UTF8-encoded databases
```
This might be a little heavy-handed now but it gives us time to consider other options for relaxing this requirement.
The decision here stems from the fact that, currently, `pgx` blindly assumes all `TEXT` Datum conversions are valid UTF8, when they might not be.  That's a problem too, but it's still not clear the RightWay to resolve that and likely wouldn't do us any good here in plrust anyways.
=> fail to create on databases that aren't `UTF8`

doc/src/install-plrust.md, doc/src/logging.md, doc/src/rules-regulations.md, doc/src/triggers.md, doc/src/use-plrust.md
This is a very simple update to modify the example create function SQL statements to use CREATE OR REPLACE in order to make copy/paste more simple since many examples share the same function schema and name combination.
=> Update create function examples to include REPLACE for easy copy/paste.

.dockerignore, .github/workflows/ci.yml, Dockerfile.try, doc/src/SUMMARY.md, doc/src/try-plrust-with-docker.md, plrust/build
Because plrust is a bit convoluted to build and run, we are introducing a Dockerfile that, when ran, should containerize everything necessary with one command so that anyone can test plrust locally. This should not ever be used for any production system, as the Postgres server being set up in this container has essentially 0 security considerations.
=> Adds Dockerfile for quick trial use of plrust

doc/src/try-plrust-with-docker.md
Just a few things that slipped by
=> Fixes up a few Docker documentation issues

plrust-trusted-pgrx/src/lib.rs, plrust/src/prosrc.rs, plrust/src/user_crate/capabilities.rs, plrust/src/user_crate/crate_variant.rs, plrust/src/user_crate/crating.rs, plrust/src/user_crate/mod.rs
Adds a `capabilities` property to our `pg_proc.prosrc` json structure and defines an enum of known function capabilities, which right now only contains `ZeroCopyArrays`.
If a function is re-compiled (really only via a pg_restore) then we'll use the set of old capabilities and adjust the wrapper code accordingly.
New functions get the `ZeroCopyArrays` capability by default, which uses `pgrx::Array<'a, T>` instead of `Vec<T>`, which old functions would have been using.
Also adds `pgrx::Array` and friends to `plrust-trusted-pgrx`.
=> Function Capabilities & Zero Copy Arrays

Cargo.lock, doc/src/config-pg.md, plrust-trusted-pgrx/Cargo.toml, plrust/Cargo.toml, plrustc/Cargo.lock, plrustc/plrustc/Cargo.toml
This is PL/Rust v1.1.2.  It contains no functional changes.  Only changes to dependencies along with new CI integrations to automatically publish `.deb` artifacts when we cut a new release.
=> prepare v1.1.2

plrust/src/user_crate/crating.rs
This causes quite some unexpected performance problems for UDFs.
=> no debug-assertions in release mode

Cargo.lock, doc/src/config-pg.md, plrust-trusted-pgrx/Cargo.toml, plrust/Cargo.toml, plrustc/Cargo.lock, plrustc/plrustc/Cargo.toml
Welcome to PL/Rust v1.1.3.  This release fixes a performance regression using functions with `ARRAY` arguments.
It also no longer compiles UDFs with `debug-assertions`.  This was, unfortunately, a development-only change that found its way into previously released versions.  
While not required, it may be desirable to `CREATE OR REPLACE` any existing `LANGUAGE plrust` functions in order to take advantage of these performance improvements.
=> Prepare v1.1.3

doc/src/SUMMARY.md, doc/src/data-types/udts.md, plrust-trusted-pgrx/src/lib.rs, plrust/src/user_crate/mod.rs
This will replace PR #57 when complete.
Here's an example:
```sql
drop type person cascade;
drop table people cascade;
create type person as (name text, age float8);
create function make_person(name text, age float8) returns person strict parallel safe language plrust as $$
let mut p = PgHeapTuple::new_composite_type("person")?;
p.set_by_name("name", name)?;
p.set_by_name("age", age)?;
Ok(Some(p))
$$;
create function get_person_name(p person) returns text strict parallel safe language plrust as $$
Ok(p.get_by_name("name")?)
$$;
create function get_person_age(p person) returns float8 strict parallel safe language plrust as $$
Ok(p.get_by_name("age")?)
$$;
create function get_person_property(p person, prop text) returns text strict parallel safe language plrust as $$
match …
```
=>  Composite type support. 

doc/src/config-lints.md, doc/src/config-pg.md, doc/src/functions/anatomy.md, plrust/src/lib.rs
As of rust 1.69, the `unaligned_references` lint is depcreated as it's just built into the compiler.
PL/Rust now uses rust 1.70, so we don't need it.  Removing it eliminates a compliation warning on user functions too.
=> Remove the `unaligned_references` lint (issue #323)

plrust/src/gucs.rs, plrust/src/user_crate/lint.rs
Loading an existing, compiled function should not require that it was previously compiled with the set of lints PL/Rust now uses for compilation.  This prohibits newer versions of PL/Rust, which might have a new lint, from executing functions created with an older version without that lint.
We do, however, continue to require the lints that are set in both the `$PLRUST_REQUIRED_LINTS` envar and the `plrust.required_lints` postgresql.conf GUC.  This is a way for the administrator to flat out **require** certain lints be applied to **every** function before it can be loaded/executed.
PL/Rust's default stance, however, is that if it was good before, it's good now, even if new lints are applied going forward.
=> Don't require a loaded function to have "compile lints" applied.

doc/src/SUMMARY.md, doc/src/config-pg.md, doc/src/dependencies.md, plrust/build, plrust/src/allow_list.rs, plrust/src/gucs.rs, plrust/src/lib.rs, plrust/src/tests.rs, plrust/src/user_crate/crating.rs, plrust/src/user_crate/mod.rs
Generally, the changes here allow a single dependency in the allow-list to have one **or more** versions specified, either as exact (`=`) or bounded ranges (`>=,<=`) or wildcards (`*`).
PL/Rust will pick the largest (newest, hopefully) entry from the allow-list that matches the function's requested version.  Depending on how either is written, the allow-list version could be used or the requested version could be used.
See the new documentation for more details.
---
As a drive-by, a number of our unit tests were tagged with `#[should_panic]` but without an expected message.  Turns out many of them were panicking but for the wrong reason!  This PR addresses these too.  
That said, the `plrust_pgloglevel_dont_allcaps_panic` test is currently set to `#[ignore]`.  Its intent is to block using …
=> In response to issue #325, rework the dependency allow-list.

plrustc/plrustc/src/lints/builtin_macros.rs, plrustc/plrustc/src/lints/extern_blocks.rs, plrustc/plrustc/src/lints/lifetime_param_trait.rs, plrustc/plrustc/src/lints/print_macros.rs, plrustc/plrustc/src/lints/static_impls.rs, plrustc/plrustc/src/lints/stdio.rs, plrustc/plrustc/src/lints/sus_trait_object.rs, plrustc/plrustc/uitests/extern_block.stderr, plrustc/plrustc/uitests/fs_macros.stderr, plrustc/plrustc/uitests/lifetime_trait.stderr, plrustc/plrustc/uitests/print_macros.stderr, plrustc/plrustc/uitests/static_impl_etc.stderr, plrustc/plrustc/uitests/static_impl_unsound.stderr, plrustc/plrustc/uitests/stdio.stderr, plrustc/plrustc/uitests/sus_trait_obj_transmute.stderr
- Fix typos.
- Make it clear that they're PL/Rust restrictions.
=> Improve plrustc lint messages 

plrustc/plrustc/src/lints/sus_trait_object.rs, plrustc/plrustc/uitests/sus_trait_obj_alias.rs, plrustc/plrustc/uitests/sus_trait_obj_alias.stderr
What a hassle. The other lints aren't sensitive to this but just by coincidence -- using aliases in them causes the I-unsound Rust issue to resolve itself. I'll see if I can figure out a less error-prone way to do those.
=> Fully resolve aliases in plrust-suspicious-trait-object

plrust-trusted-pgrx/src/lib.rs
These functions provide accessors, generally, for Postgres' various representations of the "current time".  `now()` is probably the most common of these.
Also adds a couple of missing traits and types from pgrx' "datetime_support" module.
=> Expose various date/time functions from pgrx

Cargo.lock, doc/src/config-pg.md, plrust-trusted-pgrx/Cargo.toml, plrust/Cargo.toml, plrustc/Cargo.lock, plrustc/plrustc/Cargo.toml
PL/Rust v1.2.0 is a brings a number of new features.  It is backwards compatible with all existing `LANGUAGE plrust` functions, both the source and compiled forms.
* Date/time/interval support by @eeeebbbbrrrr in https://github.com/tcdi/plrust/pull/316
PL/Rust v1.2.0 now supports Postgres `date`, `time`, `time with time zone`, `timestamp`, `timestamp with time zone`, and `interval` types as both function arguments and return types.
These types map to similarly named Rust types via `plrust-trusted-pgrx` and are fairly feature complete.  Please see the [data types](https://tcdi.github.io/plrust/data-types.html) documentation for their mappings.
* Expose various date/time functions from pgrx by @eeeebbbbrrrr in https://github.com/tcdi/plrust/pull/316
PL/Rust now exposes Postgres' various …
=> prepare-v1.2.0

.github/workflows/nightly.yml
I forgot to add a critical piece to the nightly build setup in the latest PL/Rust release. These changes address that.
=> Fixes nightly build YAML

Cargo.lock, doc/src/config-pg.md, plrust-trusted-pgrx/Cargo.toml, plrust/Cargo.toml, plrustc/Cargo.lock, plrustc/plrustc/Cargo.toml
This is PL/Rust v1.2.1.  It is a minor patch release bringing in new upstream dependencies.  Specifically, `pgrx v0.9.6` which fixes a bug with Datum to Date conversions.
=> Prepare v1.2.1

plrustc/README.md, plrustc/plrustc/src/main.rs
We no longer have to manually search for the sysroot, as of https://github.com/rust-lang/rust/pull/103660 it should be auto-detected from first the arguments passed, followed by locating it based on the location of the rustc_driver dynamic library.
This means we don't support configuring it via the environment anymore, but I don't believe anybody was explicitly using this anyway. Regardless, if they were configuring it to a different value than we locate with this function, it was almost certainly wrong. Still, we should make a note in the next release notes about it.
Thanks to @jyn514 for pointing this out to me!
=> Significantly simplify sysroot configuration

doc/src/config-lints.md, doc/src/config-pg.md, plrust/src/gucs.rs, plrust/src/lib.rs
This just fixes some inaccuracies in the docs and code comments that were missed when we changed how `plrust.required_lints` is applied in #327
=> correct docs and code comments around the `plrust.required_lints` GUC

Cargo.lock, plrust-trusted-pgrx/Cargo.toml, plrust/Cargo.toml, plrust/src/tests.rs
A critical bug concerning handling arrays with an initial null element was discovered in pgrx versions 0.8.0 to 0.9.6, recommending an upgrade to 0.9.7 as soon as is possible.
=> Upgrade to pgrx 0.9.7

Cargo.lock, doc/src/config-pg.md, plrust-trusted-pgrx/Cargo.toml, plrust/Cargo.toml, plrustc/Cargo.lock, plrustc/plrustc/Cargo.toml
This is PL/Rust v1.2.2.  It is a minor release that fixes a likely crashing bug when arrays of "varlena" types (`text`, `varchar`) are used a) used as function arguments, b) iterated, and c) contain at least one leading NULL element.
It is highly suggested that users upgrade to v1.2.2.
* Significantly simplify sysroot configuration by @thomcc in https://github.com/tcdi/plrust/pull/342
* correct docs and code comments around the `plrust.required_lints` GUC by @eeeebbbbrrrr in https://github.com/tcdi/plrust/pull/341
* Feike/toolchain fix by @feikesteenbergen in https://github.com/tcdi/plrust/pull/343
* Fix Array crashing bug by upgrading to pgrx 0.9.7 by @workingjubilee in https://github.com/tcdi/plrust/pull/344
**Full Changelog**: https://github.com/tcdi/plrust/compare/v1.2.1...v1.2.2
=> bump version to v1.2.2

plrust/src/tests.rs, plrustc/plrustc/src/lints/sus_trait_object.rs, plrustc/plrustc/uitests/sus_trait_object_gat.rs, plrustc/plrustc/uitests/sus_trait_object_gat.stderr
Thanks to @compiler-errors for helping me out here, this is much cleaner too.
Fixes #348  (we still may want to turn lints entirely off when compiling dependencies, but fixing it for real is better, and trying to parse a bunch of things out of the rustc args felt hairy without a bit more testing).
=> Use `typeck_results.node_type` to resolve the type in suspicious trait object lint

plrust/src/tests.rs, plrustc/plrustc/src/lints/sus_trait_object.rs, plrustc/plrustc/uitests/sus_trait_object_gat.rs, plrustc/plrustc/uitests/sus_trait_object_gat.stderr
This time for the correct branch...
=> Use `typeck_results.node_type` to resolve the type in suspicious trait object lint (#349)

doc/src/config-lints.md, plrust/src/lib.rs, plrustc/plrustc/src/lints/closure_trait_impl.rs, plrustc/plrustc/src/lints/fn_ptr.rs, plrustc/plrustc/src/lints/mod.rs, plrustc/plrustc/src/lints/utils.rs, plrustc/plrustc/uitests/static_closure.rs, plrustc/plrustc/uitests/static_closure.stderr
This sucked to write, but should be good enough. It will catch a lot of external crates incorrectly though, without the refinement.
=> Add a lint for closure trait impls

Cargo.lock, plrust/Cargo.toml, plrust/src/tests.rs
tempfile provides functions for tempdirs too,
so we do not need an old, deprecated dep.
This also gets rid of a minor security advisory,
not actually exploitable in our usage.
=> Drop old tempdir dep

doc/src/dependencies.md, plrust/src/gucs.rs
Since there is no technical to set `plrust.allowed_dependencies` to `Postmaster` context which requires engine restart to change its value, we can change its context to `sighup` such that the guc can be modified dynamically to provide more flexibility when using allowlisted crates.
---
- Origin value is `/tmp/old.toml`
```
(23-07-19 16:04:25) [~]
$ > psql -d postgres -c "show plrust.allowed_dependencies"
plrust.allowed_dependencies
-----------------------------
/tmp/old.toml
(1 row)
```
- Change value to `/tmp/new.toml`
```
(23-07-19 16:04:27) [~]
$ > vim pg_data/postgresql.conf
(23-07-19 16:04:37) [~]
$ > cat pg_data/postgresql.conf | grep plrust.allowed_dependencies
plrust.allowed_dependencies = '/tmp/new.toml'
```
- Reload engine and new value is applied
```
(23-07-19 16:04:43) [~]
$ > …
```
=> Change plrust.allowed_dependencies to sighup context

.github/docker/Dockerfile.debian-artifact-build
=> Carry forward exit code of `id` command

doc/book.toml, doc/src/install-plrust-on-debian-ubuntu.md, plrust/build, plrustc/build.sh, plrustc/plrustc/src/main.rs, plrustc/plrustc/uitests/ice_hook.rs, plrustc/plrustc/uitests/ice_hook.stderr, plrustc/plrustc/uitests/tuple_struct_self_pat_box.stderr, plrustc/plrustc/uitests/tuple_struct_self_pat_local_priv.stderr, plrustc/rust-toolchain.toml, rust-toolchain.toml
This had an associated CVE so it seems important. The `postgrestd` side of the update is at https://github.com/tcdi/postgrestd/pull/48, and is just about as trivial as this one (only hard part was realizing that `git subtree pull` doing nothing was actually not an error).
Closes #359, since this PR supercedes that one and includes all its commits
=> Bump to Rust 1.71.1

.github/workflows/ci.yml, Cargo.lock, plrust-tests/Cargo.toml, plrust-trusted-pgrx/Cargo.toml, plrust/Cargo.toml, plrust/src/allow_list.rs, plrust/src/gucs.rs, plrust/src/lib.rs, plrust/src/user_crate/cargo.rs, plrust/src/user_crate/lint.rs, plrustc/Cargo.lock, plrustc/plrustc/Cargo.toml
These are the updates for the v1.2.5 release, which includes updating to pgrx v0.10.0 and pg16rc1 support.
=> Prepare v1.2.5

plrust/build
Addresses: https://github.com/tcdi/plrust/issues/377
When plrust goes through a release cycle, occasionally (read: pretty much "almost" every time) we forget to update the hard-coded pgrx version in the `plrust/build` script due to the fact that our automated release tooling does not consider nor modify the script file. With the changes in this PR, we programmatically get the pgrx version using `cargo tree` and some unix utils magic so that nobody has to think about updating that value ever again upon release.
=> Updates plrust/build to programmatically get pgrx version

doc/book.toml, doc/src/install-plrust-on-debian-ubuntu.md, plrust/build, plrustc/build.sh, plrustc/plrustc/uitests/ice_hook.stderr, plrustc/rust-toolchain.toml, rust-toolchain.toml
Depends on https://github.com/tcdi/postgrestd/pull/51
=> Update Rust to 1.73.0

Cargo.lock, plrust-tests/Cargo.toml, plrust-trusted-pgrx/Cargo.toml, plrust/Cargo.toml, plrustc/Cargo.lock, plrustc/plrustc/Cargo.toml
Welcome to PL/Rust v1.2.7.  This is a small feature release that adds the ability to call user defined functions (UDFs) from a `LANGUAGE plrust` function.
As a contrived example, perhaps your database has a `LANGUAGE sql` function like:
```sql
CREATE OR REPLACE FUNCTION sum_array(a int[]) RETURNS int STRICT LANGUAGE sql AS $$ 
SELECT sum(e) FROM unnest(a) e 
$$;
```
And you wish to call it from a PL/Rust function.  Well, now you can!  
```sql
CREATE OR REPLACE FUNCTION transform_array(a int[]) RETURNS int STRICT LANGUAGE plrust AS $$
// add one to every element of `a`, the input argument array, collecting into a new Vec
let a = a.into_iter().map(|e| e.unwrap_or(0) + 1).collect::<Vec<_>>();  
// call the existing "sum_array(int[])" function to sum the values of `a`
Ok(fn_call("sum_array", …
```
=> Prepare v1.2.7

.github/docker/Dockerfile.debian-artifact-build, .github/scripts/install_cargo_pgrx.sh, .github/workflows/docs.yml, Cargo.lock, Dockerfile.try, plrust-tests/Cargo.toml, plrust-trusted-pgrx/Cargo.toml, plrust/Cargo.toml, plrustc/Cargo.lock, plrustc/plrustc/Cargo.toml
No code changes, only a version bump.
Cutting this release to account for a little CI bitrot.
=> update version to 1.2.8

Cargo.lock, plrust-tests/Cargo.toml, plrust-trusted-pgrx/Cargo.toml, plrust/Cargo.toml, plrustc/Cargo.lock, plrustc/plrustc/Cargo.toml
No code changes, only a version bump.
Cutting this release to account for a little CI bitrot.
=> update version to 1.2.8 (#404)
